USE UNIVER;
GO

-- 1. Справочники
CREATE TABLE FACULTY
(
    FACULTY CHAR(10) NOT NULL PRIMARY KEY,
    FACULTY_NAME VARCHAR(50) NOT NULL DEFAULT ('???')
);
GO

CREATE TABLE AUDITORIUM_TYPE
(
    AUDITORIUM_TYPE CHAR(10) NOT NULL PRIMARY KEY,
    AUDITORIUM_TYPENAME VARCHAR(30) NULL
);
GO

CREATE TABLE PROFESSION
(
    PROFESSION CHAR(20) NOT NULL PRIMARY KEY,
    FACULTY CHAR(10) NOT NULL,
    PROFESSION_NAME VARCHAR(100) NULL,
    QUALIFICATION VARCHAR(50) NULL,
    CONSTRAINT FK_PROFESSION_FACULTY FOREIGN KEY (FACULTY) REFERENCES FACULTY(FACULTY)
);
GO

CREATE TABLE PULPIT
(
    PULPIT CHAR(20) NOT NULL PRIMARY KEY,
    PULPIT_NAME VARCHAR(100) NULL,
    FACULTY CHAR(10) NOT NULL,
    CONSTRAINT FK_PULPIT_FACULTY FOREIGN KEY (FACULTY) REFERENCES FACULTY(FACULTY)
);
GO

CREATE TABLE SUBJECT
(
    SUBJECT CHAR(10) NOT NULL PRIMARY KEY,
    SUBJECT_NAME VARCHAR(100) NULL UNIQUE,
    PULPIT CHAR(20) NOT NULL,
    CONSTRAINT FK_SUBJECT_PULPIT FOREIGN KEY (PULPIT) REFERENCES PULPIT(PULPIT)
);
GO

CREATE TABLE AUDITORIUM
(
    AUDITORIUM CHAR(20) NOT NULL PRIMARY KEY,
    AUDITORIUM_TYPE CHAR(10) NOT NULL,
    AUDITORIUM_CAPACITY INT NOT NULL DEFAULT (1),
    AUDITORIUM_NAME VARCHAR(50) NULL,
    CONSTRAINT FK_AUDITORIUM_TYPE FOREIGN KEY (AUDITORIUM_TYPE) REFERENCES AUDITORIUM_TYPE(AUDITORIUM_TYPE),
    CONSTRAINT CHK_AUDITORIUM_CAPACITY CHECK (AUDITORIUM_CAPACITY BETWEEN 1 AND 300)
);
GO

-- 2. Таблица групп: COURSE вычисляемая, но НЕ PERSISTED (GETDATE() недетерминированен)
CREATE TABLE [GROUP]
(
    IDGROUP INT NOT NULL PRIMARY KEY,
    FACULTY CHAR(10) NOT NULL,
    PROFESSION CHAR(20) NOT NULL,
    YEAR_FIRST SMALLINT NULL,
    COURSE AS (CONVERT(TINYINT, DATEPART(YEAR, GETDATE()) - YEAR_FIRST + 1)),
    CONSTRAINT FK_GROUP_FACULTY FOREIGN KEY (FACULTY) REFERENCES FACULTY(FACULTY),
    CONSTRAINT FK_GROUP_PROFESSION FOREIGN KEY (PROFESSION) REFERENCES PROFESSION(PROFESSION),
    CONSTRAINT CHK_GROUP_YEARFIRST CHECK (YEAR_FIRST IS NULL OR YEAR_FIRST < DATEPART(YEAR, GETDATE()) + 2)
);
GO

-- 3. Студенты (ссылается на [GROUP])
CREATE TABLE STUDENT
(
    IDSTUDENT INT NOT NULL IDENTITY(1000,1) PRIMARY KEY,
    IDGROUP INT NOT NULL,
    [NAME] NVARCHAR(100) NULL,
    BDAY DATE NULL,
    STAMP ROWVERSION NOT NULL,
    INFO XML NULL,
    FOTO VARBINARY(MAX) NULL,
    CONSTRAINT FK_STUDENT_GROUP FOREIGN KEY (IDGROUP) REFERENCES [GROUP](IDGROUP)
);
GO

-- 4. Преподаватели
CREATE TABLE TEACHER
(
    TEACHER CHAR(10) NOT NULL PRIMARY KEY,
    TEACHER_NAME VARCHAR(100) NULL,
    GENDER CHAR(1) NULL,
    PULPIT CHAR(20) NOT NULL,
    CONSTRAINT FK_TEACHER_PULPIT FOREIGN KEY (PULPIT) REFERENCES PULPIT(PULPIT),
    CONSTRAINT CHK_TEACHER_GENDER CHECK (GENDER IN (N'м', N'ж'))
);
GO

-- 5. Оценки
CREATE TABLE PROGRESS
(
    SUBJECT CHAR(10) NOT NULL,
    IDSTUDENT INT NOT NULL,
    PDATE DATE NULL,
    NOTE INT NULL,
    CONSTRAINT FK_PROGRESS_SUBJECT FOREIGN KEY (SUBJECT) REFERENCES SUBJECT(SUBJECT),
    CONSTRAINT FK_PROGRESS_STUDENT FOREIGN KEY (IDSTUDENT) REFERENCES STUDENT(IDSTUDENT),
    CONSTRAINT CHK_PROGRESS_NOTE CHECK (NOTE BETWEEN 1 AND 10)
);
GO
