--1
USE UNIVER;
SELECT AUDITORIUM_TYPE.AUDITORIUM_TYPENAME,
MAX(AUDITORIUM.AUDITORIUM_CAPACITY) AS ÌÀÊÑÈÌÀËÜÍÀß_ÂÌÅÑÒÈÌÎÑÒÜ,
AVG(AUDITORIUM.AUDITORIUM_CAPACITY) AS ÑÐÅÄÍßß_ÂÌÅÑÒÈÌÎÑÒÜ,
MIN(AUDITORIUM.AUDITORIUM_CAPACITY) AS ÌÈÍÈÌÀËÜÍÀß_ÂÌÅÑÒÈÌÎÑÒÜ
FROM AUDITORIUM_TYPE INNER JOIN AUDITORIUM
ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE 
GROUP BY AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
--2
USE UNIVER
SELECT s.range_label, s.cnt
FROM (
  SELECT
    CASE
      WHEN NOTE BETWEEN 9 AND 10 THEN '9-10'
      WHEN NOTE BETWEEN 7 AND 8  THEN '7-8'
      WHEN NOTE BETWEEN 5 AND 6  THEN '5-6'
      WHEN NOTE BETWEEN 1 AND 4  THEN '1-4'
      ELSE 'other'
    END AS range_label,
    COUNT(*) AS cnt,
    MAX(NOTE) AS range_max
  FROM PROGRESS
  GROUP BY
    CASE
      WHEN NOTE BETWEEN 9 AND 10 THEN '9-10'
      WHEN NOTE BETWEEN 7 AND 8  THEN '7-8'
      WHEN NOTE BETWEEN 5 AND 6  THEN '5-6'
      WHEN NOTE BETWEEN 1 AND 4  THEN '1-4'
      ELSE 'other'
    END
) s
ORDER BY s.range_max DESC;
--3
USE UNIVER;
SELECT
  F.FACULTY_NAME,
  P.PROFESSION_NAME,
  G.COURSE,
  ROUND(AVG(CAST(PR.NOTE AS FLOAT)), 2) AS AVG_NOTE
FROM [GROUP] G
  INNER JOIN PROFESSION P ON G.PROFESSION = P.PROFESSION
  INNER JOIN FACULTY   F ON P.FACULTY   = F.FACULTY
  INNER JOIN STUDENT   S ON S.IDGROUP   = G.IDGROUP
  INNER JOIN PROGRESS  PR ON PR.IDSTUDENT= S.IDSTUDENT
GROUP BY
  F.FACULTY_NAME,
  P.PROFESSION_NAME,
  G.COURSE
ORDER BY
  AVG_NOTE DESC;
--4
USE UNIVER;
SELECT
  F.FACULTY_NAME,
  P.PROFESSION_NAME,
  G.COURSE,
  ROUND(AVG(CAST(PR.NOTE AS FLOAT)), 2) AS AVG_NOTE
FROM [GROUP] G
  INNER JOIN PROFESSION P ON G.PROFESSION = P.PROFESSION
  INNER JOIN FACULTY   F ON P.FACULTY   = F.FACULTY
  INNER JOIN STUDENT   S ON S.IDGROUP   = G.IDGROUP
  INNER JOIN PROGRESS  PR ON PR.IDSTUDENT= S.IDSTUDENT 
  WHERE 
  PR.[SUBJECT] LIKE '%ÑÓÁÄ%' OR PR.[SUBJECT] LIKE '%ÎÀèÏ%'
GROUP BY
  F.FACULTY_NAME,
  P.PROFESSION_NAME,
  G.COURSE
ORDER BY
 AVG_NOTE DESC;
--5
USE UNIVER;
GO

SELECT
  pr.PROFESSION_NAME AS Ñïåöèàëüíîñòü,
  pg.SUBJECT         AS Äèñöèïëèíà,
  ROUND(AVG(CAST(pg.NOTE AS FLOAT)), 2) AS Ñðåäíÿÿ_îöåíêà
FROM FACULTY f
  INNER JOIN PROFESSION pr ON pr.FACULTY = f.FACULTY
  INNER JOIN [GROUP] g    ON g.PROFESSION = pr.PROFESSION
  INNER JOIN STUDENT s    ON s.IDGROUP = g.IDGROUP
  INNER JOIN PROGRESS pg  ON pg.IDSTUDENT = s.IDSTUDENT
WHERE f.FACULTY_NAME = N'ÒÎÂ'
GROUP BY
  pr.PROFESSION_NAME,
  pg.SUBJECT
ORDER BY
  pr.PROFESSION_NAME,
  pg.SUBJECT;
--6
SELECT
  SUBJECT,
  SUM(CASE WHEN NOTE = 8 THEN 1 ELSE 0 END) AS cnt_8,
  SUM(CASE WHEN NOTE = 9 THEN 1 ELSE 0 END) AS cnt_9
FROM PROGRESS
GROUP BY SUBJECT
HAVING
  SUM(CASE WHEN NOTE = 8 THEN 1 ELSE 0 END) > 0
  OR SUM(CASE WHEN NOTE = 9 THEN 1 ELSE 0 END) > 0
ORDER BY (SUM(CASE WHEN NOTE = 9 THEN 1 ELSE 0 END) + SUM(CASE WHEN NOTE = 8 THEN 1 ELSE 0 END)) DESC;
