--1 
CREATE VIEW [Преподаватель]
as select TEACHER.TEACHER AS КОД, 
TEACHER.TEACHER_NAME AS ИМЯ,
TEACHER.GENDER,
TEACHER.PULPIT AS КАФЕДРА
FROM TEACHER

SELECT * FROM  Преподаватель

--2
CREATE VIEW [КОЛИЧЕСТВО_КАФЕДР]
AS SELECT
  F.FACULTY_NAME AS ИМЯ_ФАКУЛЬТЕТА,
  COUNT(*) AS КОЛИЧЕСТВО
FROM PULPIT P
  INNER JOIN FACULTY F ON F.FACULTY = P.FACULTY
GROUP BY F.FACULTY_NAME;

SELECT * FROM КОЛИЧЕСТВО_КАФЕДР

--3
CREATE VIEW Аудитории
AS SELECT
  t.AUDITORIUM_TYPENAME,
  a.AUDITORIUM_NAME
FROM AUDITORIUM a
JOIN AUDITORIUM_TYPE t ON a.AUDITORIUM_TYPE = t.AUDITORIUM_TYPE
WHERE t.AUDITORIUM_TYPENAME = N'Лекционная';

SELECT * FROM [Аудитории]
--4
CREATE VIEW [Аудитории_ЛК]
AS SELECT
  t.AUDITORIUM_TYPENAME,
  a.AUDITORIUM_NAME,
  a.AUDITORIUM
FROM AUDITORIUM a
JOIN AUDITORIUM_TYPE t ON a.AUDITORIUM_TYPE = t.AUDITORIUM_TYPE
WHERE t.AUDITORIUM_TYPENAME = N'Лекционная';


SELECT * FROM [Аудитории_ЛК]
--5
CREATE VIEW Дисциплины AS
SELECT
  t.SUBJECT      AS КОД,
  t.SUBJECT_NAME AS НАИМЕНОВАНИЕ,
  t.PULPIT       AS КОД_КАФЕДРЫ
FROM (
  SELECT TOP 100 PERCENT
    SUBJECT,
    SUBJECT_NAME,
    PULPIT
  FROM SUBJECT
  ORDER BY SUBJECT_NAME
) AS t;

SELECT * FROM [Дисциплины]

--6

ALTER VIEW dbo.КОЛИЧЕСТВО_КАФЕДР
(
  ИМЯ_ФАКУЛЬТЕТА,
  КОЛИЧЕСТВО
)
WITH SCHEMABINDING
AS
SELECT
  F.FACULTY_NAME,
  COUNT_BIG(*) AS КОЛИЧЕСТВО
FROM dbo.PULPIT AS P
JOIN dbo.FACULTY AS F
  ON F.FACULTY = P.FACULTY
GROUP BY F.FACULTY_NAME;
